### ISSUE TITLE
user input is repeated in every response

### ISSUE THREAD

**Issue by pjirsa** [microsoft/Damu#52]
when a user asks additional questions in the chat app, the initial question is repeated in the response.
![image](https://github.com/user-attachments/assets/d15b68f8-a807-428d-bbcd-31cfef6b53c7)

**Comment by cajetzer** [comment]
Actually I think it's the assistant's responses that are repeated in every response, not the initial question. 

![image](https://github.com/user-attachments/assets/bc6c992c-6396-4b55-838d-0f804a467b62)
